#!/bin/sh

HOST="i586-mingw32msvc"

export PREFIX="/usr/${HOST}"
export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"

usage() {
	echo "Usage: ${0} --installdir PATH [ARGS]..."
	echo "PATH is an absolute path"
	echo "[ARGS]... are passed verbatim to configure"
}

if test "${#}" -lt "2"; then

	# Show help message
	if test "${1}" = "--help"; then
		usage
		exit 0
	else
		usage >&2
		exit 1
	fi
fi

# Only --installdir is allowed as first arg
if test "${1}" != "--installdir"; then
	usage >&2
	exit 1
fi

INSTALLDIR="${2}"

# Make sure the path is absolute
absolute=`echo "${INSTALLDIR}" | grep '^/.*$'`
if test "x${absolute}" = "x"; then
	echo "${0}: PATH must be absolute" >&2
	exit 1
fi

# Discard the first two args
shift
shift

# Call configure
`dirname ${0}`/configure \
	--host "${HOST}" \
	--prefix "${INSTALLDIR}" \
	--bindir "${INSTALLDIR}" \
	${*}
