#!/bin/sh

TARGET="i586-mingw32msvc"

PREFIX="/usr/${TARGET}"
export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"

`dirname ${0}`/configure \
	--target=${TARGET} --host=${TARGET} \
	--prefix=${PREFIX} ${*}
